### ISSUE TITLE
Felt is 251 bits

### ISSUE THREAD

**Issue by milancermak** [a5f9t4/cairo-by-example#3]
Hi, in the guide, you compare a [felt to a 252 bit uint](https://github.com/a5f9t4/cairo-by-example/blob/main/src/pages/basics/types.tsx#L116). However, the [size of a felt is 251 bit](https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/definitions/constants.py#L7).

**Comment by ghost** [comment]
Thanks for pointing out!

I was following this data types guide https://perama-v.github.io/cairo/examples/data_types/

Will change right now!

**Comment by milancermak** [comment]
Thanks for pointing out the source. I was thinking about this and I probably misled you (and myself as well).

The way *I* think about a felt is a 251 bit uint, but that's not quite correct. A 252 bit uint isn't either, because the max value a felt can hold (P) is `2**251 < P < 2**252` where P is `2**251 + 17 * 2**192 + 1` ([docs](https://www.cairo-lang.org/docs/how_cairo_works/cairo_intro.html), [src](https://github.com/starkware-libs/cairo-lang/blob/fc97bdd8322a7df043c87c371634b26c15ed6cee/src/starkware/crypto/starkware/crypto/signature/pedersen_params.json#L20)). So it doesn't fit in a 251 bit word, but can't have all the values of a 252 bit word either.

However, for practical purposes, thinking about it as a 251 or 252 bit uint is a good enough approximation. Sorry about the confusion.
